### PR TITLE
adds $search for regex-based queries

### PR DESCRIPTION
**Pull request by alvin**

### CODE REVIEW

**Comment by ekryski** [comment]
👍 thanks @alvin! Anyone on @feathersjs/core-team have any objection to using `$match` instead of `$search` or `$like`? I actually prefer `$match`. If not, I'll merge and cut a new minor.

**Comment by alvin** [comment]
Oops, the commit msg should read $match, not $select :)

**Comment by ekryski** [comment]
@alvin no problem. You could always do `git commit --amend -m "adds $match for regex-based queries"`.

@alvin Have you implemented this in a fork of a database adapter? The other two pieces are:

- add a test to the common service tests
- and actually implement the usage in the db adapters (we can roll these out over time)

**Comment by alvin** [comment]
I'm working on a $match implementation in the rethinkdb adapter, but
thought I'd throw this little PR out first to see what the appetite for
moving this way in core is, vs moving my implementation to an extension.

If someone from core was willing to create a test for a regex matching
method, then I could ensure my rethink fork passes (feels like that might
be useful for QA given this would be a new core feature).

Thoughts?

**Comment by ekryski** [comment]
Yes this was definitely on the [roadmap](https://github.com/feathersjs/feathers/issues/299), so good timing. We called it `$search` but we'll wait a day to see if anyone else has an opinion on the naming.

We had also documented it in a few of the database repos, like [feathers-mongoose](https://github.com/feathersjs/feathers-mongoose/issues/50).

**Comment by ekryski** [comment]
I think one of us can add a test and bump the version over the next few days. Would be sweet to get this squared away early in the release. 😄

**Comment by alvin** [comment]
Sounds good. I'm a-okay with "$search" too... factors to consider seem to
be:

   - How many target databases use a method named $match vs. $search?
   - Conversely, "$search" is a simpler/broader abstraction, perhaps that
   is better for an abstraction layer?
   - Would the future include a situation where a simple wildcard/text
   match for "$search" wants to co-exist alongside a regex-powered "$match"?

**Comment by ekryski** [comment]
Related to #12

**Comment by ekryski** [comment]
> How many target databases use a method named $match vs. $search?

Not sure. Probably doesn't matter too much as we'll just map it. We do that for all the special query params already.

> Conversely, "$search" is a simpler/broader abstraction, perhaps that is better for an abstraction layer?

That's sort of why I proposed it, because $match sort of implies regex (at least to me) whereas we depending on the database type we might utilize other mechanisms (`iLike`, full text search, etc.).

> Would the future include a situation where a simple wildcard/text match for "$search" wants to co-exist alongside a regex-powered "$match"?

Possibly, and somewhat related to my answer above. We'll probably just start with regex but it might evolve into more database specific constructs based on performance/matching requirements.

**Comment by daffl** [comment]
Closing. Sorry for not merging this but after some discussion in https://github.com/feathersjs/feathers/issues/334#issuecomment-260834107 we decided to leave search up to the individual database adapters.

**Pull request closed without merging**
